// Generated by gencpp from file squad/Kiwi.msg
// DO NOT EDIT!


#ifndef SQUAD_MESSAGE_KIWI_H
#define SQUAD_MESSAGE_KIWI_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace squad
{
template <class ContainerAllocator>
struct Kiwi_
{
  typedef Kiwi_<ContainerAllocator> Type;

  Kiwi_()
    : w1(0.0)
    , w2(0.0)
    , w3(0.0)  {
    }
  Kiwi_(const ContainerAllocator& _alloc)
    : w1(0.0)
    , w2(0.0)
    , w3(0.0)  {
  (void)_alloc;
    }



   typedef float _w1_type;
  _w1_type w1;

   typedef float _w2_type;
  _w2_type w2;

   typedef float _w3_type;
  _w3_type w3;




  typedef boost::shared_ptr< ::squad::Kiwi_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::squad::Kiwi_<ContainerAllocator> const> ConstPtr;

}; // struct Kiwi_

typedef ::squad::Kiwi_<std::allocator<void> > Kiwi;

typedef boost::shared_ptr< ::squad::Kiwi > KiwiPtr;
typedef boost::shared_ptr< ::squad::Kiwi const> KiwiConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::squad::Kiwi_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::squad::Kiwi_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace squad

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'squad': ['/home/connie/robo_squad/src/squad/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::squad::Kiwi_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::squad::Kiwi_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::squad::Kiwi_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::squad::Kiwi_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::squad::Kiwi_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::squad::Kiwi_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::squad::Kiwi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd82aec785cf5731a7d25a0042e76809";
  }

  static const char* value(const ::squad::Kiwi_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbd82aec785cf5731ULL;
  static const uint64_t static_value2 = 0xa7d25a0042e76809ULL;
};

template<class ContainerAllocator>
struct DataType< ::squad::Kiwi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "squad/Kiwi";
  }

  static const char* value(const ::squad::Kiwi_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::squad::Kiwi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 w1\n\
float32 w2\n\
float32 w3\n\
";
  }

  static const char* value(const ::squad::Kiwi_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::squad::Kiwi_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.w1);
      stream.next(m.w2);
      stream.next(m.w3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Kiwi_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::squad::Kiwi_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::squad::Kiwi_<ContainerAllocator>& v)
  {
    s << indent << "w1: ";
    Printer<float>::stream(s, indent + "  ", v.w1);
    s << indent << "w2: ";
    Printer<float>::stream(s, indent + "  ", v.w2);
    s << indent << "w3: ";
    Printer<float>::stream(s, indent + "  ", v.w3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SQUAD_MESSAGE_KIWI_H
