// Generated by gencpp from file squad/robot_position_msg.msg
// DO NOT EDIT!


#ifndef SQUAD_MESSAGE_ROBOT_POSITION_MSG_H
#define SQUAD_MESSAGE_ROBOT_POSITION_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace squad
{
template <class ContainerAllocator>
struct robot_position_msg_
{
  typedef robot_position_msg_<ContainerAllocator> Type;

  robot_position_msg_()
    : x(0)
    , y(0)
    , frontx(0)
    , fronty(0)
    , angle(0.0)  {
    }
  robot_position_msg_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , frontx(0)
    , fronty(0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef int32_t _frontx_type;
  _frontx_type frontx;

   typedef int32_t _fronty_type;
  _fronty_type fronty;

   typedef float _angle_type;
  _angle_type angle;




  typedef boost::shared_ptr< ::squad::robot_position_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::squad::robot_position_msg_<ContainerAllocator> const> ConstPtr;

}; // struct robot_position_msg_

typedef ::squad::robot_position_msg_<std::allocator<void> > robot_position_msg;

typedef boost::shared_ptr< ::squad::robot_position_msg > robot_position_msgPtr;
typedef boost::shared_ptr< ::squad::robot_position_msg const> robot_position_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::squad::robot_position_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::squad::robot_position_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace squad

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'squad': ['/home/connie/robo_squad/src/squad/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::squad::robot_position_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::squad::robot_position_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::squad::robot_position_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::squad::robot_position_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::squad::robot_position_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::squad::robot_position_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::squad::robot_position_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "28ee68e7cd1a8a51c576061a459afeaa";
  }

  static const char* value(const ::squad::robot_position_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x28ee68e7cd1a8a51ULL;
  static const uint64_t static_value2 = 0xc576061a459afeaaULL;
};

template<class ContainerAllocator>
struct DataType< ::squad::robot_position_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "squad/robot_position_msg";
  }

  static const char* value(const ::squad::robot_position_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::squad::robot_position_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x\n\
int32 y\n\
int32 frontx\n\
int32 fronty\n\
float32 angle\n\
";
  }

  static const char* value(const ::squad::robot_position_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::squad::robot_position_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.frontx);
      stream.next(m.fronty);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_position_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::squad::robot_position_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::squad::robot_position_msg_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "frontx: ";
    Printer<int32_t>::stream(s, indent + "  ", v.frontx);
    s << indent << "fronty: ";
    Printer<int32_t>::stream(s, indent + "  ", v.fronty);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SQUAD_MESSAGE_ROBOT_POSITION_MSG_H
