
define swarm position
(
  pose [ 0.0 0.0 0.0 0.0 ]
  localization "gps"

  #size [ 0.2552 0.2552 0.40 ]
  size [ 0.8 0.8 0.40 ]
  origin [ 0.0 0.0 0.0 0.0 ]
  gui_nose 1
  drive "omni"
  color "gray"

  #block
  #(
  #  points 6
  #  point[0] [1 0]
  #  point[1] [0.5 0.86602]
  #  point[2] [-0.5 0.86602]
  #  point[3] [-1 0]
  #  point[4] [-0.5 -0.86602]
  #  point[5] [0.5 -.86602]
  #  z [0 1]
  #)
  #size [5 5 5]
  
  
)

